config/routes.rb
Rails.application.routes.draw do
devise_for :users, controllers: {
        registrations: 'users/registrations'
      }

  namespace :api do
    post :upload_image, to: 'utils#upload_image'
    resources :users, only: [] do
      member do
        post :follow
      end
    end

    resources :stories, only: [] do
      member do 
        post :clap
        post :bookmark
      end
    end
  end

  resources :users, only: [] do
    collection do
      get :pricing # /users/picing
      get :payment # /users/payment
      post :pay # /users/pay
    end
  end

  resources :stories do
    resources :comments, only: [:create]
  end

  get '@:username/:story_id', to: 'pages#show', as: 'story_page'

  get '@:username', to: 'pages#user', as: 'user_page'

  root 'pages#index'
end

app/views/pages/_comment.html.erb
<article class="comment">
  <span class="profile">
    <%= image_tag comment.user.avatar.variant(resize: '50X50'), class: 'avatar' if @story.user.avatar.attached? %>
    <span class="username"><%= comment.user.username %></span>
  </span>
  <%= simple_format(comment.content) %>     
</article>

app/views/pages/_comment_area.html.erb
<section class="comment-editor">
  <% if user_signed_in? %>

  <%= form_with model: comment, url: story_comments_path(story), class: 'comment_form', remote: true do |form| %>
    <%= form.text_area :content, rows: 5, class: 'textarea is-small'  %>
    <%= form.button '送出', class: 'button is-primary is-fullwidth ' %>
  <% end %>

  <% else %>
    <%= link_to '請先登入', new_user_session_path, class: 'button is-success' %>
    <%= link_to '會員註冊', new_user_registration_path, class: 'button is-info' %>
  <% end %>
</section>

app/views/pages/index.html.erb
<section class="columns">
        <!-- left -->
        <section class="column">
          <article>
          <% @newest_story.each do |story|  %>

            <% if story.cover_image.attached? %>
            <figure class="media">
              <%= image_tag story.cover_image.variant(resize: '350X350') %>
            </figure>
            <% end%>
            
            <h2 class="title is-5"><%= link_to story.title , story_page_path(story.user.username, story), class: 'has-text-grey-dark' %></h2>
            
            <p class="content">
            <%= strip_tags(story.content).truncate(200) %>
            </p>
            <footer>
               <p><%= link_to story.user.username, user_page_path(story.user.username),class: 'has-text-grey-dark' %> | <%= time_ago_in_words(story.created_at) %></p>
            </footer>

            <% end %>
          </article>
        </section>
        <!-- left -->
        <!-- middle -->
        <section class="column">
        <% @newest_story_from_number2.each do |story|  %>
          <article class="media">

            <% if story.cover_image.attached? %>
            <figure class="media-left">
              <%= image_tag story.cover_image.variant(resize: '100X100') %>
            </figure>
            <% end%>
            
            <div class="media-content">
              <h2 class="title is-5"><%= link_to story.title , story_page_path(story.user.username, story), class: 'has-text-grey-dark' %></h2>
              <footer>
               <p><%= link_to story.user.username, user_page_path(story.user.username),class: 'has-text-grey-dark' %> | <%= time_ago_in_words(story.created_at) %></p>
              </footer>
            </div>
          </article>
        <% end %>
        </section>
        <!-- middle -->
        <!-- right -->
        <section class="column">
          <article>

          <% @story_most_clap.each do |story|  %>

            <% if story.cover_image.attached? %>
            <figure class="media">
              <%= image_tag story.cover_image.variant(resize: '350X300') %>
            </figure>
            <% end%>

            <h2 class="title is-5"><%= link_to story.title , story_page_path(story.user.username, story), class: 'has-text-grey-dark' %></h2>

            <p class="content">
            <%= strip_tags(story.content).truncate(20) %>
            </p>

            <footer>
              <p><%= link_to story.user.username, user_page_path(story.user.username),class: 'has-text-grey-dark' %> | <%= time_ago_in_words(story.created_at) %></p>
            </footer>
            <% end %>
          </article>
        </section>
        <!-- right -->
      </section>

      <hr>

      <section class="columns">

        <!-- article list -->
        <section class="column is-two-thirds">

          <% @stories.each do |story|  %>
          <article class="media">
            <div class="media-content">
              <h2 class="title is-4"><%= link_to story.title , story_page_path(story.user.username, story), class: 'has-text-grey-dark' %></h2>
              <p class="content"><%= strip_tags(story.content).truncate(200) %></p>
              <footer>
                <p><%= link_to story.user.username, user_page_path(story.user.username),class: 'has-text-grey-dark' %> | <%= time_ago_in_words(story.created_at) %></p>
              </footer>
            </div>

            <% if story.cover_image.attached? %>
            <figure class="media-right">
              <%= image_tag story.cover_image.variant(resize: '150X150') %>
            </figure>
            <% end%>

          </article>
          <% end %>

        </section>
        <!-- article list -->

        <section class="column">
          <h2 class="title is-4">Popular on Medium</h2>
          <hr>

          <% @stories_most_clap.each_with_index do |story, index|  %>
          <article class="media">
            <div class="media-left"><%= index +1 %></div>
            <div class="media-content">
              <h3 class="title is-6"><%= link_to story.title , story_page_path(story.user.username, story), class: 'has-text-grey-dark' %></h3>
              <footer>
                <p class="content"><%= strip_tags(story.content).truncate(20) %></p>
              </footer>
            </div>
          </article>
          <% end %>
  
        </section>
      </section>

app/views/pages/show.html.erb
<section class="columns has-text-centered story-content">
  <section class="column is-offset-3 is-6">
    <h1 class="title"><%= @story.title %></h1>

    <span class="profile" data-controller="user">
      <%= image_tag @story.user.avatar.variant(resize: '50X50'), class: 'avatar' if @story.user.avatar.attached? %>
      <span class="username"><%= link_to @story.user.username, user_page_path(@story.user.username),class: 'has-text-grey-dark' %></span>

      <%= link_to '#', class: 'follow-button', data: {action: 'user#follow', user: @story.user.id, target: 'user.followButton'} do %>
      <%= (user_signed_in? && current_user.follow?(@story.user)) ? 'Followed' : 'Follow' %>
      <% end %>

      <%= link_to '#', class: 'bookmark-button', data: {action: 'user#bookmark' , slug: @story.slug } do %>
      <% if user_signed_in? && current_user.bookmark?(@story) %>
        <i class="fa-solid fa-bookmark" data-target=" user.bookmark"></i>
      <% else %>
        <i class="fa-regular fa-bookmark" data-target=" user.bookmark"></i>
      <% end %>
    <% end %>
  </span>

    <article class="content">
      <%= image_tag @story.cover_image.variant(resize: '1000X500' ), class: 'cover-image' if @story.cover_image.attached? %>

      <%= @story.content.html_safe %>

      <footer data-controller="story">
        <%= link_to '#', class: 'clapButton is-size-2 has-text-primary', data: { action:'story#addClap', slug: @story.slug } do %>
      <i class="fa-solid fa-hands-clapping"></i>
      <span class="clapCount" 
      data-story-target="clapCount" ><%= @story.clap %></span>
      <% end %>
      </footer>
    </article>
    <hr>
    <section class="comments">
      <h2>留言</h2>

      <%= render 'comment_area', story: @story, comment: @comment %>

      <section class="comment-list">
        <%= render partial: 'comment', collection: @comments %>

      </section>
    </section>
  </section>
</section>

app/views/pages/user.html.erb
<h1 class="title">故事列表</h2>

<% @stories.each do |story| %>
 <div class="content">
   <h2 class="title">

     <h2 class="title is-4"><%= link_to story.title , story_page_path(story.user.username, story), class: 'has-text-grey-dark' %></h2>
   </h2>
   <p><%= strip_tags(story.content).truncate(200) %></p>
   <p><%= story.user.username %> | <%= time_ago_in_words(story.created_at) %></p>
 </div>
<hr>

  <% end %>